service: LannChainBook-ChatGTPSlackFunction
frameworkVersion: '3'

privider:
  name: aws
  resion: ap-northeast-1
  stage: dev
  iam:
    role:
      statement:
        - Effect: Allow
          Action: 
            - lambda:InvokeFunction
          Resource: '*'

package:
  patterns:
    - '!.venv/**'
    - '!.env'
    - '!.gitignore'
    - '!.python-version'
    - '!.git/**'

functions:
  app:
    name: LangCHainBook-ChatGPTSlackFunction-${sls:stage}-app
    handler: app.handler
    runtime: python3.10
    memorySize: 512
    timeout: 900
    url: true

plugins:
  - serverless-python-requirements
  - serverlss-dotenv-plugins